### ISSUE TITLE
can this on run at linux?

### ISSUE THREAD

**Issue by ice6** [mindbox-cloud/data-linq#37]
It seems that is can not run on linux server.

**Comment by Youkai-no-nii-chan** [comment]
It runs perfectly fine on our Kubernets cluster where we use docker with linux. 
Do you have some errors in your environment?

**Comment by ice6** [comment]
> It runs perfectly fine on our Kubernets cluster where we use docker with linux. Do you have some errors in your environment?

thanks for the clarification.
